// Users
export const CAN_VIEW_USERS = "CAN_VIEW_USERS";
export const CAN_CREATE_USERS = "CAN_CREATE_USERS";
export const CAN_REMOVE_USERS = "CAN_REMOVE_USERS";

// Transactions
export const CAN_VIEW_TRANSACTIONS = "CAN_VIEW_TRANSACTIONS";
export const CAN_VIEW_METRICS = "CAN_VIEW_METRICS";


export const ALL_PERMISSIONS = [
    CAN_CREATE_USERS,
    CAN_REMOVE_USERS,
    CAN_VIEW_TRANSACTIONS,
    CAN_VIEW_METRICS,
]
